### ISSUE TITLE
Remove $this->managerInterface from SaveShippingAfterObserver

### ISSUE THREAD

**Issue by cieslix** [macopedia/magento2-allegro#32]
Please remove `$this->managerInterface` from `SaveShippingAfterObserver` lines: 117-119 
If there is an error when adding waybill number to allegro this makes fatal error and shipment is not saved in magento database  

https://github.com/macopedia/magento2-allegro/blob/4c77501244c758d535730c0805283903bbd7f7fc/Observer/SaveShippingAfterObserver.php#L117

**Comment by sgradzielewski** [comment]
Fatal error is made probably because `managerInterface` property is not defined. @mstrzyzewski please take care of this bug: define missing property and test this case.
