### ISSUE TITLE
Uncaught Error: Cannot instantiate abstract class 

### ISSUE THREAD

**Issue by mrk-dzie** [macopedia/magento2-allegro#47]
Po zainstalowaniu modułu i próbie przejścia na stronę zawierającą informacje o błędach podczas importowania strona się nie wyświetla zwracając błąd HTTP 500.
W logach serwera znalazłem taki błąd:
[STDERR] PHP Fatal error:  Uncaught Error: Cannot instantiate abstract class Macopedia\Allegro\Controller\Adminhtml\Orders\Index in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121

**Comment by mrk-dzie** [comment]
Strona wczytuje się normalnie po usunięciu abstract sprzed nazwy klasy \Macopedia\Allegro\Controller\Adminhtml\Orders\Index

**Comment by cieslix** [comment]
@mrk-dzie poprawione w https://github.com/macopedia/magento2-allegro/commit/80c8a674ebf3419786a3082b71543d69941211b9 (dokładnie od wersji v4.0.1)
