### ISSUE TITLE
importLogger.ERROR: Wrong response received while fetching events data

### ISSUE THREAD

**Issue by michalzimniak** [macopedia/magento2-allegro#57]
Plugin version: current from master branch
Magento version: 2.3.5-p1

After installation and creating api keys on allegro I get only those errors in logs:

`importLogger.ERROR: Wrong response received while fetching events data [] []
`
and connection status looks like this:

![image](https://user-images.githubusercontent.com/7513244/81280103-4f4a1b80-9058-11ea-83d6-a012906d25bb.png)

**Comment by cieslix** [comment]
After you save credentials client id, client secret, you have to use button "Connect with Allegro account" this is part of OAuth flow.

**Comment by michalzimniak** [comment]
I tried to do it that way, but I get error page on Allegro:

![image](https://user-images.githubusercontent.com/7513244/81793175-4a2e1600-9509-11ea-8776-1673486befa2.png)

**Comment by cieslix** [comment]
So it means, that you have incorrect "Redirect Uri/Adresy przekierowań". Please set up it in your allegro app: https://apps.developer.allegro.pl/ or https://apps.developer.allegro.pl.allegrosandbox.pl/
It must be something like http(s)://shop.dot.url:port_if_needed/YourAdminPanelUri/allegro/system/authenticate/
You must replace "shop.dot.url", ":port_if_needed" and "YourAdminPanelUri" according to your's Magento2 configuration.

**Comment by michalzimniak** [comment]
Started to work, thanks for your support. Closing this issue.
