### ISSUE TITLE
How to skip entering all Allegro attributes 

### ISSUE THREAD

**Issue by michalzimniak** [macopedia/magento2-allegro#62]
Hi,

If there is any option to make change the behavior of Allegro attributes during creating an auction? At this moment all attributes are required. What to do if I don't want or don't know all of them? Example: Category Laptops and battery capacity and number of cells. How to skip it?

**Comment by michalzimniak** [comment]
Hi,

Can I help you with that somehow?

**Comment by michalzimniak** [comment]
Hi,

Its possible to add a change to your plugin?

**Comment by cieslix** [comment]
Hi @michalzimniak,

Some of attributes are required and this is not hardcoded in the our module, it comes from Allegro API (it is fetch on prompt for specific cateogry). If you would try to skip it Allegro API will return error.

Of course you can fork this module and add your changes there and test it by your own.
