### ISSUE TITLE
Send tracking information to Allegro

### ISSUE THREAD

**Issue by donald8998** [macopedia/magento2-allegro#76]
Dzień dobry,
Zainstalowałem release 4.3.4 i niestety wysyłanie numerów przesyłek do allegro mi nie działa (instalowane na czystym magento 2.3.2). Wysyłkę robiłem dpd , carrier:id powinien się zgadzać "dpd" jednak nr nie jest przesyłany do allegro.
W opisie jest rysunek https://github.com/macopedia/magento2-allegro/blob/master/README/sendTrackingInformation1.png - widać na nim pola "Origin of the order","external service","external id". W instalowanej wersji jednak tych pól nie ma - czy to jest powodem dla którego numer przesyłki nie jest wysyłany do allegro ?
Pozdrawiam

**Comment by mstrzyzewski** [comment]
Dzień dobry,
proszę sprawdzić, czy opcja 'Wysyłka numerów przesyłek aktywna' w konfiguracji wtyczki jest włączona oraz, czy w logach nie wystąpił żaden błąd (var/log/allegro-exceptions.log).

Pola z sekcji 'Origin of the order' zawierają m.in. id zamówienia z Allegro, które jest wykorzystywane do wysyłki numerów przesyłek. Jednak umieszczenie tych pól w widoku zamówienia nie musi być dokładnie takie samo jak na załączonym obrazku, mogą one znajdować się na samym dole zamówienia.
