### ISSUE TITLE
Errors during compilation - Magento 2.3.1

### ISSUE THREAD

**Issue by maxdemage** [macopedia/magento2-allegro#8]
During **bin/magento setup:di:compile**
those Errors occur:

```
Errors during compilation:
         Macopedia\Allegro\Ui\AllegroOffer\Form\CreateDataProvider
                 Incompatible argument type: Required type: string. Actual type: \Macopedia\Allegro\Ui\AllegroOffer\Form\name; File:
 /var/www/html/app/code/Macopedia/Allegro/Ui/AllegroOffer/Form/CreateDataProvider.php

         Macopedia\Allegro\Ui\AllegroOffer\Form\EditDataProvider
                 Incompatible argument type: Required type: string. Actual type: \Macopedia\Allegro\Ui\AllegroOffer\Form\name; File:
 /var/www/html/app/code/Macopedia/Allegro/Ui/AllegroOffer/Form/EditDataProvider.php

```

Quick investigation:

- Ui/AllegroOffer/Form/EditDataProvider.php
- Ui/AllegroOffer/Form/CreateDataProvider.php

Those 2 files have wrong php-doc for constructors (_name_ variable is not declared as string, and rest of the string variables);

Is:

`* @param $name`

Should be:

`* @param string $name`

**Comment by n0kit31** [comment]
Fix in https://github.com/macopedia/magento2-allegro/commit/6193a55eab2c29f06994f582acfe75c6d33ea074

Thanks!
