### ISSUE TITLE
Connect with Allegro account, 404 not found on magento

### ISSUE THREAD

**Issue by antoineanorra** [macopedia/magento2-allegro#81]
Hello,

When I click on "Connect with Allegro account", I have an 404 error on Magento, you can see the picture.
What can I do to solve the problem? (I have already disable key csrf protection because I have multiple redirections)

![image](https://user-images.githubusercontent.com/48593504/93496484-8f2ae480-f90f-11ea-96e3-8aec376f0ac3.png)

Magento 2.3.1 - RabbitMQ

Thx

**Comment by agilepartnerantoine** [comment]
The problem is still there, can someone answer me?

**Comment by cieslix** [comment]
Hi @agilepartnerantoine on Magento 2.3.x we have tested this module and there was no issues like yours. Please check your application configuration on the Allegro and before pressing button "connect with allegro account" please save configuration in backend - i know it is not user friendly.
![image](https://user-images.githubusercontent.com/6729521/96875845-fe987480-1477-11eb-8709-a672aab74d38.png)

**Comment by agilepartnerantoine** [comment]
Hi @cieslix 

I have already check the configuration and read all the ReadMe on your github, but the redirection go to the admin panel with 404 error, you can't close this issue

**Comment by cieslix** [comment]
@agilepartnerantoine did you use correct callback url in Allegro APP configuration ?

**Comment by agilepartnerantoine** [comment]
Yes, I use the correct callback url but first I disabled key csrf protection in magento because the callback can't access without this option disabled, can you confirm that?

**Comment by cieslix** [comment]
disabling CSRF protection is not needed, but maybe your backend account is not an admin with full access ?

**Comment by agilepartnerantoine** [comment]
If I disable CSRF protection, i will be infinite redirect. I'm admin and root with full acess because it's my magento

**Comment by cieslix** [comment]
@agilepartnerantoine we have already couple users of this module and no one is disabling CRSF in backend. Please check your user's role in system -> users -> user roles / all users
![image](https://user-images.githubusercontent.com/6729521/96880718-cbf17a80-147d-11eb-94c2-7fb4b53b9bf4.png)
If this doesn't help set Magento2 to `developer mode` https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-mode.html and check logs.
